// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA67vt8KkpWt5NnVmj5B5_B61SvOl61InA',
    appId: '1:454768255710:android:48b163b2d5cc742c86184f',
    messagingSenderId: '454768255710',
    projectId: 'glamourme',
    databaseURL: 'https://glamourme-default-rtdb.firebaseio.com',
    storageBucket: 'glamourme.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFhpzpnB_Rricu_14jL9mOYmU03U4hwY0',
    appId: '1:454768255710:ios:5c4cb725af5e47a086184f',
    messagingSenderId: '454768255710',
    projectId: 'glamourme',
    databaseURL: 'https://glamourme-default-rtdb.firebaseio.com',
    storageBucket: 'glamourme.appspot.com',
    androidClientId: '454768255710-h5tnqrcl39uis0rvit5hde7gcem335da.apps.googleusercontent.com',
    iosClientId: '454768255710-5u9inbvtjgnvgbs5ki3042el8tmb6ot4.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodrescueApp',
  );

}